# official ubuntu image (https://hub.docker.com/_/ubuntu) as base
FROM ubuntu:latest

# Update and upgrade
RUN apt-get update && apt-get upgrade -y

# Install software properties common
RUN apt-get install -y software-properties-common

# adds ubuntu universe and multiverse repos
RUN add-apt-repository universe -y \
	&& add-apt-repository multiverse -y

# install essential dev tools
RUN apt-get install -y \
	build-essential \
	cmake \
	bash \
	curl \
	rlwrap \
	vim \
	git \
	libopengl0 \
	sudo \
	wget

# Adds dependencies that are usually required when building Python from source
RUN apt-get install -y \
	pkg-config \
	python3-tk \
	libsqlite3-dev \
	libncurses5-dev \
	libgdbm-dev \
	libbz2-dev \
	libdb-dev \
	uuid-dev \
	libffi-dev \
	liblzma-dev \
	libreadline-dev \
	libssl-dev \
	tk-dev \
	zlib1g-dev \
	libnss3-dev

# Install zsh
RUN apt-get install -y zsh

# set zsh as the default shell
RUN chsh -s $(which zsh)

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# install python 3.12 from source and clean up installation files
RUN wget https://www.python.org/ftp/python/3.12.5/Python-3.12.5.tar.xz \
	-O /tmp/Python-3.12.5.tar.xz \
	&& cd /tmp/ \
	&& tar -xvf Python-3.12.5.tar.xz \
	&& cd Python-3.12.5 \
	&& ./configure \
	&& make \
	&& sudo make install \
	&& cd .. \
	&& rm -rf Python-3.12.5

# install pip
RUN apt-get install -y python3-pip

# install python packages
RUN pip3 install bpython \
	&& pip3 install black \
	&& pip3 install requests \
	&& pip3 install flask


# default location
WORKDIR $HOME

CMD [ "zsh" ]
