# Ubuntu image with python3, zsh, nodejs, typescript, vim

# official ubuntu image (https://hub.docker.com/_/ubuntu) as base
FROM ubuntu:latest

# Update and upgrade
RUN apt-get update && apt-get upgrade -y

# Install software properties common
RUN apt-get install -y software-properties-common

# adds ubuntu universe and multiverse repos
RUN add-apt-repository universe -y \
	&& add-apt-repository multiverse -y

# install essential dev tools
RUN apt-get install -y \
	build-essential \
	cmake \
	bash \
	curl \
	rlwrap \
	vim \
	git \
	libopengl0 \
	sudo \
	wget

# Adds dependencies that are usually required when building Python from source
RUN sudo apt-get install -y \
	pkg-config \
	python3-tk \
	libsqlite3-dev \
	libncurses5-dev \
	libgdbm-dev \
	libbz2-dev \
	libdb-dev \
	uuid-dev \
	libffi-dev \
	liblzma-dev \
	libreadline-dev \
	libssl-dev \
	tk-dev \
	zlib1g-dev \
	libnss3-dev

# Install zsh
RUN sudo apt-get install -y zsh

# set zsh as the default shell
RUN chsh -s $(which zsh)

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Create 'ubuntu' user if they do not exist, and don't give a password
RUN id -u ubuntu &>/dev/null || \
	useradd -m -s /bin/zsh ubuntu \
	&& echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Switch to the 'ubuntu' user, and go to their home directory
USER ubuntu

# install python 3.12 from source and clean up installation files
RUN wget https://www.python.org/ftp/python/3.12.5/Python-3.12.5.tar.xz \
	-O /tmp/Python-3.12.5.tar.xz \
	&& cd /tmp/ \
	&& tar -xvf Python-3.12.5.tar.xz \
	&& cd Python-3.12.5 \
	&& ./configure \
	&& make \
	&& sudo make install \
	&& cd .. \
	&& sudo rm -rf Python-3.12.5 \
	&& rm Python-3.12.5.tar.xz

# go to user's home directory (useful for later config files)
RUN cd /home/ubuntu

# install pip
RUN sudo apt-get install -y python3-pip

# install python packages
RUN pip3 install bpython \
	&& pip3 install black \
	&& pip3 install requests \
	&& pip3 install flask

# install nodejs
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - \
	&& sudo apt-get install nodejs -y

# install typescript
RUN sudo npm install -g typescript

# clean up old dependencies
RUN sudo apt-get -y autoremove

# default location
WORKDIR /home/ubuntu/

CMD [ "zsh" ]
